In [1]:
import numpy as np

In [2]:
a=np.array([0,1,2,3,4])

In [3]:
type(a)

numpy.ndarray

In [10]:
b=np.arange(1000)

In [11]:
a**2

array([ 0,  1,  4,  9, 16])

In [12]:
%timeit [i**2 for i in range(1000)]

153 μs ± 5.34 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
%timeit b**2

3.73 μs ± 41.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
a.ndim

1

In [15]:
a.shape

(5,)

In [16]:
len(a)

5

In [17]:
c=np.array([[1,2,3,4],
           [5,6,7,8]])

In [18]:

c.ndim

2

In [19]:
c.shape

(2, 4)

In [20]:
len(c)

2

In [25]:
d=np.array([[[1,2,3],[1,2,3]],[[2,3,4],[2,3,4]],[[3,4,5],[3,4,5]],[[4,4,4],[4,4,4]]])

In [26]:
d.ndim

3

In [27]:
d.shape

(4, 2, 3)

In [30]:
x=np.linspace(0,1,6)

In [31]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.twos((3,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [39]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [40]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
np.diag(np.diag(a))

array([0, 1, 2, 3, 4])

In [45]:
a.dtype

dtype('int32')

In [46]:
a=np.arange(10,dtype='int64')

In [47]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [49]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
b=np.arange(10,dtype='float64')

In [51]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
c=np.array([1+4j,2+3j])

In [54]:
c.dtype

dtype('complex128')

In [55]:
np.array([True,False,True]).dtype

dtype('bool')

In [56]:
np.array(['Aashraey','Raj','Karega']).dtype

dtype('<U8')

In [57]:
a[2]

2

In [58]:
a[-1]

9

In [59]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [60]:
x=np.diag([1,2,3,4])

In [61]:
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [64]:
x[2:3]

array([[0, 0, 3, 0]])

In [65]:
np.random.rand(4)

array([0.16885833, 0.20688653, 0.59516823, 0.96837209])

In [66]:
np.random.randn(4)

array([-0.82342805, -0.24594057, -0.4618908 ,  0.75492525])

In [67]:
a=np.arange(0,100,10)

In [68]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
b=a[:3]

In [70]:
b

array([ 0, 10, 20])

In [72]:
np.shares_memory(a,b)

True

In [73]:
c=a[:3].copy()

In [74]:
c

array([ 0, 10, 20])

In [75]:
np.shares_memory(b,c)

False

In [76]:
a=np.random.randint(0,20,15)

In [77]:
a

array([ 0, 14, 15,  4, 18,  5, 16,  6, 13, 15, 15,  9, 14, 18,  6])

In [78]:
mask= a%2==0

In [79]:
a[mask]

array([ 0, 14,  4, 18, 16,  6, 14, 18,  6])

In [80]:
a[[2,4,5,2,4,2]]

array([15, 18,  5, 15, 18, 15])

In [81]:
a

array([ 0, 14, 15,  4, 18,  5, 16,  6, 13, 15, 15,  9, 14, 18,  6])

In [82]:
a[mask]=1

In [83]:
a

array([ 1,  1, 15,  1,  1,  5,  1,  1, 13, 15, 15,  9,  1,  1,  1])

In [85]:
data=np.loadtxt('Populations.txt')

In [86]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [87]:
year,hare,lynx,carrot=data.T

In [88]:
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [89]:
population=data[:,1:]

In [90]:
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [91]:
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [92]:
population.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [94]:
a=np.tile(np.arange(0,40,10),(3,1))

In [95]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [97]:
a=a.T

In [98]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [99]:
b=np.tile(np.array([0,1,2]),(4,1))

In [100]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [101]:
a+b


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [102]:
b=np.array([0,1,2])

In [103]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [119]:
a=np.arange(0,40,10)

In [120]:
a

array([ 0, 10, 20, 30])

In [121]:
a=a[:,np.newaxis]

In [122]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [123]:
a.shape

(4, 1)

In [124]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [125]:
b

array([0, 1, 2])

In [126]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [127]:
a=np.arange(4*3*2)

In [128]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [129]:
a.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [139]:
x=np.arange(6)

In [140]:
x

array([0, 1, 2, 3, 4, 5])

In [142]:
x.resize(8,refcheck=False)

In [143]:
x

array([0, 1, 2, 3, 4, 5, 0, 0])

In [146]:
x.resize(4,refcheck=False)

In [147]:
x

array([0, 1, 2, 3])